name: Build Firmwares

on: [push]

permissions:
  id-token: write
  contents: write

jobs:
  build-sketches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .

      - name: Install arduino
        run: |
          sudo apt-get update
          sudo apt-get install arduino-cli
        shell: bash
        
      - name: Build firmwares
        run: ./build-all.sh
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: firmwares
          path: "*/firmware.uf2"
