name: Build Firmwares

on: [push]

permissions:
  id-token: write
  contents: write

jobs:
  build-sketches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .

      - name: Install arduino
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/bin
          rmdir bin
        shell: bash
        
      - name: Build firmwares
        run: ./build-all.sh
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: firmwares
          path: ./*/*.uf2

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*/*.uf2
          prerelease: true
          draft: true
          make_latest: false
          